apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-08-14T06:07:44Z"
  labels:
    kustomize.toolkit.fluxcd.io/name: podinfo
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: podinfo
  namespace: default
  resourceVersion: "13630"
  uid: 20eb84a1-e3ec-4242-b366-465c0cfd6d52
spec:
  clusterIP: 10.111.176.10
  clusterIPs:
  - 10.111.176.10
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 9898
    protocol: TCP
    targetPort: http
  - name: grpc
    port: 9999
    protocol: TCP
    targetPort: grpc
  selector:
    app: podinfo
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  name: podinfo-service
spec:
  type: LoadBalancer
  selector:
    app: podinfo
  ports:
  - name: http
    port: 80
    targetPort: 8080
